/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useCard18 = () => {
  let data: any = {};
  const handleButton = (): any => {};
  const Description = (): any => {};
  const text2 = (): any => {};
  const handleClose = (): any => {};

  let fns: any = {handleButton, Description, text2, handleClose};
  return {data, fns};
}

export default useCard18;