/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';

 
const Frame141 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `42px 21px`,  
  boxSizing: `border-box`,  
  height: "100%",  
  width: "100%",  
});
  
const Frame15 = styled("div")({  
  backgroundColor: `rgba(255, 0, 0, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  width: `90px`,  
  height: `91px`,  
  margin: `0px`,  
  overflow: `hidden`,  
});
  
const Frame16 = styled("div")({  
  backgroundColor: `rgba(255, 0, 0, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  width: `90px`,  
  height: `91px`,  
  margin: `0px 0px 0px 26px`,  
  overflow: `hidden`,  
});
  
const Frame17 = styled("div")({  
  backgroundColor: `rgba(255, 0, 0, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  width: `90px`,  
  height: `91px`,  
  margin: `0px 0px 0px 26px`,  
  overflow: `hidden`,  
});
 
function Frame14(props) {
  return (
    <Frame141 className={props.className} >
      <Frame15 >
      </Frame15>
      <Frame16 >
      </Frame16>
      <Frame17 >
      </Frame17>
    </Frame141>
  );
}

export default Frame14;
