/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useFrame4 = () => {
  let data: any = {};
  const hello = (): any => {
  return "48"};

  let fns: any = {hello};
  return {data, fns};
}

export default useFrame4;
