/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { Button, Link } from '@mui/material';
import { styled } from '@mui/material/styles';
import SoEasy from 'components/SoEasy/SoEasy';
import { HomeProps } from 'types';

 
const Property1Desktop: any = styled("div")({  
  backgroundColor: `rgba(23, 23, 23, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  width: "100%",  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const HeroBg: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1440px`,  
  margin: `0px`,  
  overflow: `hidden`,  
});
  
const HeroContent: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `40px 0px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const HeroDesktop: any = styled("div")({  
  backgroundImage: `url(assets/food/images/hero_desktop_1.png)`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `80px 180px 60px 110px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
  overflow: `hidden`,  
});
  
const HeroAll: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const ActionsIcon: any = styled("img")({  
  height: `50px`,  
  width: `50px`,  
  margin: `0px`,  
});
  
const HeroContent1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 140px 0px 0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 14px`,  
});
  
const Frame125: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `110px`,  
  letterSpacing: `-5px`,  
  textDecoration: `none`,  
  lineHeight: `96px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `110px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `110px`,  
  textTransform: `none`,  
  background: `linear-gradient(-90deg, rgba(254, 136, 136, 1) 27.162295143312438%, rgba(128, 102, 255, 1) 97.8620029592611%)`,  
  backgroundClip: `text`,  
  WebkitBackgroundClip: `text`,  
  WebkitTextFillColor: `transparent`,  
  margin: `0px`,  
});
  
const HeroSub: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px 50px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `23px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `24px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `34px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const ButtonOutlined: any = styled(Button)({  
  width: `180px`,  
  margin: `0px 0px 0px 34px`,  
});
  
const Sec4: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px 180px 48px 180px`,  
  boxSizing: `border-box`,  
  width: `1440px`,  
  margin: `50px 0px 0px 0px`,  
});
  
const Frame1251: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Sec4Text: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Subtitle: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon1: any = styled("img")({  
  height: `14px`,  
  width: `14px`,  
  margin: `0px`,  
});
  
const NewWay: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  width: `417px`,  
  margin: `0px 0px 0px 8px`,  
});
  
const Frame1252: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `18px 0px 0px 0px`,  
});
  
const Q1Line: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Achieve: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Product: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  background: `linear-gradient(-90deg, rgba(254, 136, 136, 1) 27.16229514331244%, rgba(128, 102, 255, 1) 97.8620029592611%)`,  
  backgroundClip: `text`,  
  WebkitBackgroundClip: `text`,  
  WebkitTextFillColor: `transparent`,  
  margin: `0px 0px 0px 6px`,  
});
  
const DevelopmentNirvana: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Dashboard: any = styled("div")({  
  backgroundImage: `url(assets/food/images/dashboard_1.png)`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  width: `608px`,  
  height: `340px`,  
  margin: `0px 0px 0px 30px`,  
});
  
const Divider: any = styled("div")({  
  backgroundColor: `rgba(46, 46, 46, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `34px 0px 0px 0px`,  
});
  
const BuildBoldPoints: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `34px 0px 0px 0px`,  
});
  
const Frame1253: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `302.67px`,  
});
  
const Icon1: any = styled("img")({  
  height: `20px`,  
  width: `20px`,  
  margin: `0px`,  
});
  
const MakeExisting: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `800`,  
  fontSize: `24px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  width: `303px`,  
  margin: `12px 0px 0px 0px`,  
});
  
const MakeExisting1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  width: `303px`,  
  margin: `12px 0px 0px 0px`,  
});
  
const Frame1254: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `302.67px`,  
});
  
const Icon2: any = styled("img")({  
  height: `20px`,  
  width: `20px`,  
  margin: `0px`,  
});
  
const BuildConsistently: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `800`,  
  fontSize: `24px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `12px 0px 0px 0px`,  
});
  
const BuildConsistently1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `12px 0px 0px 0px`,  
});
  
const Frame1255: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `302.67px`,  
});
  
const Icon3: any = styled("img")({  
  height: `20px`,  
  width: `20px`,  
  margin: `0px`,  
});
  
const IterateBetween: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `800`,  
  fontSize: `24px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `12px 0px 0px 0px`,  
});
  
const IterateBetween1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `12px 0px 0px 0px`,  
});
  
const SecStats: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px 180px 50px 180px`,  
  boxSizing: `border-box`,  
  width: `1440px`,  
  margin: `50px 0px 0px 0px`,  
});
  
const Divider1: any = styled("div")({  
  backgroundColor: `rgba(46, 46, 46, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `0px`,  
});
  
const BuildBoldPoints1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `34px 0px 0px 0px`,  
});
  
const Stat1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Icon4: any = styled("img")({  
  height: `76px`,  
  width: `76px`,  
  margin: `0px`,  
});
  
const Txt: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 16px`,  
});
  
const StatNum1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `800`,  
  fontSize: `42px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const StatDesc1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Stat2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Icon5: any = styled("img")({  
  height: `76px`,  
  width: `76px`,  
  margin: `0px`,  
});
  
const Txt1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 12px`,  
});
  
const StatNum2: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `800`,  
  fontSize: `42px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const StatDesc2: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Stat3: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Icon6: any = styled("img")({  
  height: `76px`,  
  width: `76px`,  
  margin: `0px`,  
});
  
const Txt2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px 0px 0px 12px`,  
});
  
const StatNum3: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `800`,  
  fontSize: `42px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const StatDesc3: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Divider2: any = styled("div")({  
  backgroundColor: `rgba(46, 46, 46, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `34px 0px 0px 0px`,  
});
  
const SecSlideshow: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px 180px 70px 180px`,  
  boxSizing: `border-box`,  
  width: `1440px`,  
  margin: `50px 0px 0px 0px`,  
});
  
const Frame1256: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Sec4Text1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Subtitle1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon2: any = styled("img")({  
  height: `14px`,  
  width: `14px`,  
  margin: `0px`,  
});
  
const NewWay1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  width: `417px`,  
  margin: `0px 0px 0px 8px`,  
});
  
const SoEasy1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `18px 0px 0px 0px`,  
});
  
const TakeDesignToLaunc2: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  width: `869px`,  
  margin: `0px`,  
});
  
const Frame1257: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc3: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  background: `linear-gradient(-90deg, rgba(254, 136, 136, 1) 27.16229514331244%, rgba(128, 102, 255, 1) 97.86200295926109%)`,  
  backgroundClip: `text`,  
  WebkitBackgroundClip: `text`,  
  WebkitTextFillColor: `transparent`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc4: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 10px`,  
});
  
const LearnMore: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `18px 0px 0px 0px`,  
});
  
const About: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Link1: any = styled(Link)({  
  color: `rgba(254, 136, 136, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0.09090909361839294px`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 5px`,  
});
  
const SoEasy2: any = styled(SoEasy)(({ theme }: any) =>({  
  alignSelf: `stretch`,  
  margin: `40px 0px 0px 0px`,  
}));
  
const Sec41: any = styled("div")({  
  backgroundImage: `url(assets/food/images/sec4_1.png)`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `111px 180px 61px 180px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `50px 0px 0px 0px`,  
});
  
const Frame1258: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1080px`,  
  margin: `0px`,  
});
  
const Sec4Text2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Subtitle2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon3: any = styled("img")({  
  height: `14px`,  
  width: `14px`,  
  margin: `0px`,  
});
  
const NewWay2: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  width: `417px`,  
  margin: `0px 0px 0px 8px`,  
});
  
const TryItHeadline: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `24px 0px 0px 0px`,  
});
  
const Frame1259: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `442px`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc5: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc6: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  background: `linear-gradient(-90deg, rgba(254, 136, 136, 1) 27.16229514331245%, rgba(128, 102, 255, 1) 97.86200295926109%)`,  
  backgroundClip: `text`,  
  WebkitBackgroundClip: `text`,  
  WebkitTextFillColor: `transparent`,  
  width: `297px`,  
  margin: `0px 0px 0px 8px`,  
});
  
const TakeDesignToLaunc7: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  width: `442px`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `18px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `24px 0px 0px 0px`,  
});
  
const ButtonOutlined1: any = styled(Button)({  
  margin: `24px 0px 0px 0px`,  
});
  
const CodeExport: any = styled("div")({  
  backgroundImage: `url(assets/food/images/Code___Export_1.png)`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  borderRadius: `6px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  width: `608px`,  
  height: `340px`,  
  margin: `0px 0px 0px 30px`,  
  overflow: `hidden`,  
});
  
const Divider3: any = styled("div")({  
  backgroundColor: `rgba(46, 46, 46, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  height: `2px`,  
  width: `1080px`,  
  margin: `34px 0px 0px 0px`,  
});
  
const BuildBoldPoints2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  width: `1080px`,  
  margin: `34px 0px 0px 0px`,  
});
  
const Frame12510: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Icon7: any = styled("img")({  
  height: `20px`,  
  width: `20px`,  
  margin: `0px`,  
});
  
const MakeExisting2: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `800`,  
  fontSize: `24px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  width: `302.67px`,  
  margin: `12px 0px 0px 0px`,  
});
  
const MakeExisting3: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  width: `302.67px`,  
  margin: `12px 0px 0px 0px`,  
});
  
const Frame12511: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Icon8: any = styled("img")({  
  height: `20px`,  
  width: `20px`,  
  margin: `0px`,  
});
  
const BuildConsistently2: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `800`,  
  fontSize: `24px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  width: `302.67px`,  
  margin: `12px 0px 0px 0px`,  
});
  
const BuildConsistently3: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  width: `302.67px`,  
  margin: `12px 0px 0px 0px`,  
});
  
const Frame126: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Icon9: any = styled("img")({  
  height: `20px`,  
  width: `20px`,  
  margin: `0px`,  
});
  
const IterateBetween2: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `800`,  
  fontSize: `24px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `28px`,  
  textTransform: `none`,  
  width: `302.67px`,  
  margin: `12px 0px 0px 0px`,  
});
  
const IterateBetween3: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0px`,  
  textDecoration: `none`,  
  lineHeight: `26px`,  
  textTransform: `none`,  
  width: `302.67px`,  
  margin: `12px 0px 0px 0px`,  
});
  
const Samples: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `121px 180px 111px 180px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `50px 0px 0px 0px`,  
});
  
const Box: any = styled("div")({  
  border: `2px solid rgba(46, 46, 46, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `12px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `40px`,  
  width: `1080px`,  
  margin: `0px`,  
});
  
const SamplesContent: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const LeftSide: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Subtitle3: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon4: any = styled("img")({  
  height: `14px`,  
  width: `14px`,  
  margin: `0px`,  
});
  
const NewWay3: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  width: `417px`,  
  margin: `0px 0px 0px 8px`,  
});
  
const TryItHeadline1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 20px 0px`,  
  boxSizing: `border-box`,  
  margin: `20px 0px 0px 0px`,  
});
  
const SeeHow: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Frame12512: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc8: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc9: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `44px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `42px`,  
  textTransform: `none`,  
  background: `linear-gradient(-90deg, rgba(254, 136, 136, 1) 27.16229514331245%, rgba(128, 102, 255, 1) 97.86200295926109%)`,  
  backgroundClip: `text`,  
  WebkitBackgroundClip: `text`,  
  WebkitTextFillColor: `transparent`,  
  width: `297px`,  
  margin: `0px`,  
});
  
const LearnMore1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `18px 0px 0px 0px`,  
});
  
const About1: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Link2: any = styled(Link)({  
  color: `rgba(254, 136, 136, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0.09090909361839294px`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 5px`,  
});
  
const RightSide: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-end`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  height: `140px`,  
  margin: `0px 0px 0px 24px`,  
});
  
const Image: any = styled("div")({  
  background: `linear-gradient(180deg, rgba(254, 254, 254, 1) -3.0616171314629196e-15%, rgba(157, 157, 157, 1) 99.99999999999997%)`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `8px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  flexGrow: `1`,  
  margin: `0px`,  
  overflow: `hidden`,  
});
  
const Thumb: any = styled("div")({  
  backgroundImage: `url(assets/food/images/thumb_2.png)`,  
  backgroundPosition: `center`,  
  backgroundSize: `contain`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  alignSelf: `stretch`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Image1: any = styled("div")({  
  background: `linear-gradient(180deg, rgba(255, 255, 255, 1) -3.0616171314629196e-15%, rgba(151, 151, 151, 1) 99.99999999999997%)`,  
  border: `1px solid rgba(255, 255, 255, 0.4)`,  
  boxSizing: `border-box`,  
  borderRadius: `8px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `8px`,  
  alignSelf: `stretch`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 24px`,  
  overflow: `hidden`,  
});
  
const Thumb1: any = styled("div")({  
  backgroundImage: `url(assets/food/images/thumb_1.png)`,  
  backgroundPosition: `center`,  
  backgroundSize: `contain`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const Image2: any = styled("div")({  
  background: `linear-gradient(180deg, rgba(255, 255, 255, 1) -3.0616171314629196e-15%, rgba(151, 151, 151, 1) 99.99999999999997%)`,  
  borderRadius: `12px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 24px`,  
  overflow: `hidden`,  
});
  
const Thumb2: any = styled("div")({  
  backgroundImage: `url(assets/food/images/thumb.png)`,  
  backgroundPosition: `center`,  
  backgroundSize: `contain`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  flexGrow: `1`,  
  margin: `0px`,  
});
  
const CompareSec: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px 180px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `50px 0px 0px 0px`,  
});
  
const Compare: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Subtitle4: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon5: any = styled("img")({  
  height: `14px`,  
  width: `14px`,  
  margin: `0px`,  
});
  
const AhedOfThePack: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  width: `417px`,  
  margin: `0px 0px 0px 8px`,  
});
  
const Frame12513: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 20px 0px`,  
  boxSizing: `border-box`,  
  margin: `24px 0px 0px 0px`,  
});
  
const TakeDesignToLaunc10: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `52px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `50px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const TakeDesignToLaunc11: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `52px`,  
  letterSpacing: `-2px`,  
  textDecoration: `none`,  
  lineHeight: `54px`,  
  textTransform: `none`,  
  background: `linear-gradient(-90deg, rgba(254, 136, 136, 1) 27.16229514331244%, rgba(128, 102, 255, 1) 97.86200295926109%)`,  
  backgroundClip: `text`,  
  WebkitBackgroundClip: `text`,  
  WebkitTextFillColor: `transparent`,  
  width: `641.49px`,  
  margin: `0px`,  
});
  
const CompareChart: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `center`,  
  alignItems: `flex-end`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `24px 0px 0px 0px`,  
});
  
const Frame122: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Row: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Frame1221: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Fpo: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 0)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  height: `61px`,  
  margin: `0px`,  
});
  
const Frame1222: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 75px`,  
});
  
const QuestLogoComparison: any = styled("img")({  
  height: `44px`,  
  width: `151.5px`,  
});
  
const LogoA: any = styled("img")({  
  height: `34px`,  
  width: `115.22px`,  
});
  
const LogoB: any = styled("img")({  
  height: `24px`,  
  width: `107px`,  
});
  
const Row1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Divider4: any = styled("div")({  
  backgroundColor: `rgba(88, 88, 88, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `0px`,  
});
  
const Frame1223: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm2: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  height: `24px`,  
  margin: `0px`,  
});
  
const Frame1224: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 70px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 75px`,  
});
  
const Checkmark: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const Checkmark1: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const Checkmark2: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const Row2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Divider5: any = styled("div")({  
  backgroundColor: `rgba(88, 88, 88, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `0px`,  
});
  
const Frame1225: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm3: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  height: `24px`,  
  margin: `0px`,  
});
  
const Frame1226: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 70px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 75px`,  
});
  
const Checkmark3: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const Checkmark4: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const XMark: any = styled("img")({  
  height: `40.01px`,  
  width: `40.01px`,  
});
  
const Row3: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Divider6: any = styled("div")({  
  backgroundColor: `rgba(88, 88, 88, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `0px`,  
});
  
const Frame1227: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm4: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  height: `48px`,  
  margin: `0px`,  
});
  
const Frame1228: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 70px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 75px`,  
});
  
const Checkmark5: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const Checkmark6: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const XMark1: any = styled("img")({  
  height: `40.01px`,  
  width: `40.01px`,  
});
  
const Row4: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Divider7: any = styled("div")({  
  backgroundColor: `rgba(88, 88, 88, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `0px`,  
});
  
const Frame1229: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm5: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  height: `48px`,  
  margin: `0px`,  
});
  
const Frame12210: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 70px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 75px`,  
});
  
const Checkmark7: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const XMark2: any = styled("img")({  
  height: `40.01px`,  
  width: `40.01px`,  
});
  
const XMark3: any = styled("img")({  
  height: `40.01px`,  
  width: `40.01px`,  
});
  
const Row5: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Divider8: any = styled("div")({  
  backgroundColor: `rgba(88, 88, 88, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `0px`,  
});
  
const Frame12211: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm6: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  height: `24px`,  
  margin: `0px`,  
});
  
const Frame12212: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 70px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 75px`,  
});
  
const Checkmark8: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const XMark4: any = styled("img")({  
  height: `40.01px`,  
  width: `40.01px`,  
});
  
const XMark5: any = styled("img")({  
  height: `40.01px`,  
  width: `40.01px`,  
});
  
const Row6: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Divider9: any = styled("div")({  
  backgroundColor: `rgba(88, 88, 88, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `0px`,  
});
  
const Frame12213: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm7: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  height: `48px`,  
  margin: `0px`,  
});
  
const Frame12214: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 70px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 75px`,  
});
  
const Checkmark9: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const XMark6: any = styled("img")({  
  height: `40.01px`,  
  width: `40.01px`,  
});
  
const XMark7: any = styled("img")({  
  height: `40.01px`,  
  width: `40.01px`,  
});
  
const Row7: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Divider10: any = styled("div")({  
  backgroundColor: `rgba(88, 88, 88, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `0px`,  
});
  
const Frame12215: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm8: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  height: `48px`,  
  margin: `0px`,  
});
  
const Frame12216: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 70px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 75px`,  
});
  
const Checkmark10: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const XMark8: any = styled("img")({  
  height: `40.01px`,  
  width: `40.01px`,  
});
  
const XMark9: any = styled("img")({  
  height: `40.01px`,  
  width: `40.01px`,  
});
  
const Row8: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const Divider11: any = styled("div")({  
  backgroundColor: `rgba(88, 88, 88, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  alignSelf: `stretch`,  
  height: `2px`,  
  margin: `0px`,  
});
  
const Frame12217: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  padding: `10px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `10px 0px 0px 0px`,  
});
  
const NeoFromQuestAiEm9: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  height: `48px`,  
  margin: `0px`,  
});
  
const Frame12218: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `space-between`,  
  alignItems: `flex-start`,  
  padding: `0px 30px 0px 70px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  margin: `0px 0px 0px 75px`,  
});
  
const Checkmark11: any = styled("img")({  
  height: `40px`,  
  width: `40px`,  
});
  
const XMark10: any = styled("img")({  
  height: `40.01px`,  
  width: `40.01px`,  
});
  
const XMark11: any = styled("img")({  
  height: `40.01px`,  
  width: `40.01px`,  
});
  
const CustomerQuote: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `100px 180px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `50px 0px 0px 0px`,  
});
  
const Box1: any = styled("div")({  
  backgroundImage: `url(assets/food/images/box.png)`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  border: `2px solid rgba(46, 46, 46, 1)`,  
  boxSizing: `border-box`,  
  borderRadius: `12px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `30px 0px 0px 0px`,  
  height: `430px`,  
  width: `850px`,  
  margin: `0px`,  
  overflow: `hidden`,  
});
  
const Text: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `40px`,  
  boxSizing: `border-box`,  
  width: `562px`,  
  margin: `0px`,  
});
  
const LeftSide1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const Subtitle5: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon6: any = styled("img")({  
  height: `14px`,  
  width: `14px`,  
  margin: `0px`,  
});
  
const CustomerLove: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  margin: `0px 0px 0px 8px`,  
});
  
const CustomerQuote1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 0px 20px 0px`,  
  boxSizing: `border-box`,  
  margin: `20px 0px 0px 0px`,  
});
  
const Quote: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `482px`,  
  margin: `0px`,  
});
  
const Company: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `28px 0px 0px 0px`,  
});
  
const EnctrLogo: any = styled("img")({  
  height: `26px`,  
  width: `109px`,  
  margin: `0px`,  
});
  
const Name: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `18px 0px 0px 0px`,  
});
  
const FullName: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `23px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  margin: `0px`,  
});
  
const Title: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(196, 196, 196, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `16px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  width: `241px`,  
  margin: `6px 0px 0px 0px`,  
});
  
const LearnMore2: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `28px 0px 0px 0px`,  
});
  
const About2: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `18px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Link3: any = styled(Link)({  
  color: `rgba(254, 136, 136, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `18px`,  
  letterSpacing: `0.09090909361839294px`,  
  lineHeight: `24px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 5px`,  
});
  
const RightSide1: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-end`,  
  alignItems: `flex-end`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  flexGrow: `1`,  
  height: `400px`,  
  margin: `0px`,  
});
  
const Luka1: any = styled("img")({  
  height: `348px`,  
  width: `368px`,  
  margin: `0px`,  
});
  
const ProductHunt: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `10px 180px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `34px 0px 0px 0px`,  
});
  
const PhImage: any = styled("div")({  
  backgroundImage: `url(assets/food/images/PH_image.png)`,  
  backgroundPosition: `center`,  
  backgroundSize: `contain`,  
  backgroundRepeat: `no-repeat`,  
  borderRadius: `12px`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `center`,  
  alignItems: `center`,  
  height: `133px`,  
  width: `632px`,  
  margin: `0px`,  
  overflow: `hidden`,  
});
  
const DiscoverSec: any = styled("div")({  
  backgroundImage: `url(assets/food/images/Discover_Sec_1.png)`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `90px 180px 0px 180px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `50px 0px 0px 0px`,  
});
  
const Frame127: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px 100px 0px 0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `0px`,  
});
  
const Subtitle6: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  margin: `0px`,  
});
  
const ActionsIcon7: any = styled("img")({  
  height: `14px`,  
  width: `12.95px`,  
  margin: `0px`,  
});
  
const NeoFromQuestAiEm10: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `700`,  
  fontSize: `12px`,  
  letterSpacing: `2px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `uppercase`,  
  width: `385.7px`,  
  margin: `0px 0px 0px 6px`,  
});
  
const DiscoverTheSpan1: any = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `64px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `56px`,  
  textTransform: `none`,  
});
  
const DiscoverTheSpan2: any = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(254, 136, 136, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `64px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `56px`,  
  textTransform: `none`,  
});
  
const DiscoverTheSpan3: any = styled("span")({  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `64px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `56px`,  
  textTransform: `none`,  
});
  
const DiscoverThe: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Articulat CF`,  
  fontWeight: `700`,  
  fontSize: `64px`,  
  letterSpacing: `-1px`,  
  textDecoration: `none`,  
  lineHeight: `56px`,  
  textTransform: `none`,  
  alignSelf: `stretch`,  
  margin: `24px 0px 0px 0px`,  
});
  
const ImportYourDifferen: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  width: `622.49px`,  
  margin: `24px 0px 0px 0px`,  
});
  
const LearnMore3: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `24px 0px 0px 0px`,  
});
  
const About3: any = styled("div")({  
  textAlign: `left`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(255, 255, 255, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0.09090909361839294px`,  
  textDecoration: `none`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  margin: `0px`,  
});
  
const Link4: any = styled(Link)({  
  color: `rgba(254, 136, 136, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Visby CF`,  
  fontWeight: `600`,  
  fontSize: `20px`,  
  letterSpacing: `0.09090909361839294px`,  
  lineHeight: `30px`,  
  textTransform: `none`,  
  margin: `0px 0px 0px 5px`,  
});
  
const ButtonOutlined2: any = styled(Button)({  
  margin: `24px 0px 0px 0px`,  
});
  
const BtmImage: any = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `center`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  alignSelf: `stretch`,  
  margin: `50px 0px 0px 0px`,  
});
  
const Sec4Image: any = styled("div")({  
  backgroundImage: `url(assets/food/images/sec4_Image_2.png)`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  height: `512px`,  
  width: `1440px`,  
  margin: `0px`,  
});
 
function Home(props: HomeProps): JSX.Element {
  return (
    <Property1Desktop className={props.className} >
      <HeroBg >
        <HeroContent >
          <HeroDesktop >
            <HeroAll >
              <ActionsIcon  src={`assets/food/images/Actions_Icon_22.png`} alt={"Actions Icon"}/>
              <HeroContent1 >
                <Frame125 >
                  <TakeDesignToLaunc >
                    {`The better way to build your`}
                      </TakeDesignToLaunc>
                  <TakeDesignToLaunc1 >
                    {`frontend`}
                      </TakeDesignToLaunc1>
                </Frame125>
                <HeroSub >
                  <NeoFromQuestAiEm >
                    {`Generate React components with clean, extendable code. 
Build and iterate on your products faster than ever.`}
                      </NeoFromQuestAiEm>
                  <ButtonOutlined variant="outlined" size="large" color="primary"    > Sign Up Now </ButtonOutlined>
                </HeroSub>
              </HeroContent1>
            </HeroAll>
          </HeroDesktop>
        </HeroContent>
      </HeroBg>
      <Sec4 >
        <Frame1251 >
          <Sec4Text >
            <Subtitle >
              <ActionsIcon1  src={`assets/food/images/Actions_Icon_21.png`} alt={"Actions Icon"}/>
              <NewWay >
                {`FRONTEND PERFECTION`}
                  </NewWay>
            </Subtitle>
            <Frame1252 >
              <Q1Line >
                <Achieve >
                  {`Achieve`}
                    </Achieve>
                <Product >
                  {`product`}
                    </Product>
              </Q1Line>
              <DevelopmentNirvana >
                {`development nirvana`}
                  </DevelopmentNirvana>
            </Frame1252>
          </Sec4Text>
          <Dashboard >
          </Dashboard>
        </Frame1251>
        <Divider >
        </Divider>
        <BuildBoldPoints >
          <Frame1253 >
            <Icon1  src={`assets/food/images/icon_21.png`} alt={"icon"}/>
            <MakeExisting >
              {`Create clean and efficient code`}
                </MakeExisting>
            <MakeExisting1 >
              {`Not only human readable, Quest-generated code is extendable to add your custom modules or business logic — as if you hand-coded it.`}
                </MakeExisting1>
          </Frame1253>
          <Frame1254 >
            <Icon2  src={`assets/food/images/icon_20.png`} alt={"icon"}/>
            <BuildConsistently >
              {`Ensure consistency across your team`}
                </BuildConsistently>
            <BuildConsistently1 >
              {`Lower technical debt in your frontend as every line of code has a purpose.
`}
                </BuildConsistently1>
          </Frame1254>
          <Frame1255 >
            <Icon3  src={`assets/food/images/icon_19.png`} alt={"icon"}/>
            <IterateBetween >
              {`Free up bandwidth for your developers`}
                </IterateBetween>
            <IterateBetween1 >
              {`Instead of tweaking the UI constantly, your developers can focus more on your core product or business logic.
`}
                </IterateBetween1>
          </Frame1255>
        </BuildBoldPoints>
      </Sec4>
      <SecStats >
        <Divider1 >
        </Divider1>
        <BuildBoldPoints1 >
          <Stat1 >
            <Icon4  src={`assets/food/images/icon_18.png`} alt={"icon"}/>
            <Txt >
              <StatNum1 >
                {`42,214,612`}
                  </StatNum1>
              <StatDesc1 >
                {`Lines of code generated`}
                  </StatDesc1>
            </Txt>
          </Stat1>
          <Stat2 >
            <Icon5  src={`assets/food/images/icon_17.png`} alt={"icon"}/>
            <Txt1 >
              <StatNum2 >
                {`153,549`}
                  </StatNum2>
              <StatDesc2 >
                {`Projects Built`}
                  </StatDesc2>
            </Txt1>
          </Stat2>
          <Stat3 >
            <Icon6  src={`assets/food/images/icon_16.png`} alt={"icon"}/>
            <Txt2 >
              <StatNum3 >
                {`28,200`}
                  </StatNum3>
              <StatDesc3 >
                {`Plugin Users`}
                  </StatDesc3>
            </Txt2>
          </Stat3>
        </BuildBoldPoints1>
        <Divider2 >
        </Divider2>
      </SecStats>
      <SecSlideshow >
        <Frame1256 >
          <Sec4Text1 >
            <Subtitle1 >
              <ActionsIcon2  src={`assets/food/images/Actions_Icon_20.png`} alt={"Actions Icon"}/>
              <NewWay1 >
                {`FIT your workflow`}
                  </NewWay1>
            </Subtitle1>
            <SoEasy1 >
              <TakeDesignToLaunc2 >
                {`So easy... `}
                  </TakeDesignToLaunc2>
              <Frame1257 >
                <TakeDesignToLaunc3 >
                  {`Become a Pro`}
                    </TakeDesignToLaunc3>
                <TakeDesignToLaunc4 >
                  {`in 15 minutes`}
                    </TakeDesignToLaunc4>
              </Frame1257>
            </SoEasy1>
            <LearnMore >
              <About >
                {`Learn more about`}
                  </About>
              <Link1 href="#" underline="hover"  >our features.</Link1>
            </LearnMore>
          </Sec4Text1>
        </Frame1256>
        <SoEasy2   />
      </SecSlideshow>
      <Sec41 >
        <Frame1258 >
          <Sec4Text2 >
            <Subtitle2 >
              <ActionsIcon3  src={`assets/food/images/Actions_Icon_19.png`} alt={"Actions Icon"}/>
              <NewWay2 >
                {`SCALES WHEN READY`}
                  </NewWay2>
            </Subtitle2>
            <TryItHeadline >
              <Frame1259 >
                <TakeDesignToLaunc5 >
                  {`Try it`}
                    </TakeDesignToLaunc5>
                <TakeDesignToLaunc6 >
                  {`risk-free`}
                    </TakeDesignToLaunc6>
              </Frame1259>
              <TakeDesignToLaunc7 >
                {`and see for yourself`}
                  </TakeDesignToLaunc7>
            </TryItHeadline>
            <NeoFromQuestAiEm1 >
              {`Component plans include a 30-day trial. `}
                </NeoFromQuestAiEm1>
            <ButtonOutlined1 variant="outlined" size="large" color="primary"    > Sign Up Now </ButtonOutlined1>
          </Sec4Text2>
          <CodeExport >
          </CodeExport>
        </Frame1258>
        <Divider3 >
        </Divider3>
        <BuildBoldPoints2 >
          <Frame12510 >
            <Icon7  src={`assets/food/images/icon_15.png`} alt={"icon"}/>
            <MakeExisting2 >
              {`Start small`}
                </MakeExisting2>
            <MakeExisting3 >
              {`Build one component and add it to your app. If you like how it works, you can build more. You don't have to switch your entire app at once.
`}
                </MakeExisting3>
          </Frame12510>
          <Frame12511 >
            <Icon8  src={`assets/food/images/icon_14.png`} alt={"icon"}/>
            <BuildConsistently2 >
              {`No vendor lock-in`}
                </BuildConsistently2>
            <BuildConsistently3 >
              {`You export the code components you generate, so you’re not locked-in. 
`}
                </BuildConsistently3>
          </Frame12511>
          <Frame126 >
            <Icon9  src={`assets/food/images/icon_13.png`} alt={"icon"}/>
            <IterateBetween2 >
              {`You own your code & 
your IP`}
                </IterateBetween2>
            <IterateBetween3 >
              {`You own whatever you build. It’s yours to do what you want.
`}
                </IterateBetween3>
          </Frame126>
        </BuildBoldPoints2>
      </Sec41>
      <Samples >
        <Box >
          <SamplesContent >
            <LeftSide >
              <Subtitle3 >
                <ActionsIcon4  src={`assets/food/images/Actions_Icon_18.png`} alt={"Actions Icon"}/>
                <NewWay3 >
                  {`Design & Code`}
                    </NewWay3>
              </Subtitle3>
              <TryItHeadline1 >
                <SeeHow >
                  <Frame12512 >
                    <TakeDesignToLaunc8 >
                      {`Check out some`}
                        </TakeDesignToLaunc8>
                    <TakeDesignToLaunc9 >
                      {`samples`}
                        </TakeDesignToLaunc9>
                  </Frame12512>
                </SeeHow>
                <LearnMore1 >
                  <About1 >
                    {`Visit our`}
                      </About1>
                  <Link2 href="#" underline="hover"  >samples page.</Link2>
                </LearnMore1>
              </TryItHeadline1>
            </LeftSide>
            <RightSide >
              <Image >
                <Thumb >
                </Thumb>
              </Image>
              <Image1 >
                <Thumb1 >
                </Thumb1>
              </Image1>
              <Image2 >
                <Thumb2 >
                </Thumb2>
              </Image2>
            </RightSide>
          </SamplesContent>
        </Box>
      </Samples>
      <CompareSec >
        <Compare >
          <Subtitle4 >
            <ActionsIcon5  src={`assets/food/images/Actions_Icon_17.png`} alt={"Actions Icon"}/>
            <AhedOfThePack >
              {`AHEAD OF THE PACK`}
                </AhedOfThePack>
          </Subtitle4>
          <Frame12513 >
            <TakeDesignToLaunc10 >
              {`Built for the most demanding`}
                </TakeDesignToLaunc10>
            <TakeDesignToLaunc11 >
              {`product teams `}
                </TakeDesignToLaunc11>
          </Frame12513>
          <CompareChart >
            <Frame122 >
              <Row >
                <Frame1221 >
                  <Fpo >
                    {`Build new applications`}
                      </Fpo>
                  <Frame1222 >
                    <QuestLogoComparison  src={`assets/food/images/Quest_logo_comparison_1.png`} alt={"Quest logo comparison"}/>
                    <LogoA  src={`assets/food/images/logo_a_2.png`} alt={"logo a"}/>
                    <LogoB  src={`assets/food/images/logo_b_2.png`} alt={"logo b"}/>
                  </Frame1222>
                </Frame1221>
              </Row>
              <Row1 >
                <Divider4 >
                </Divider4>
                <Frame1223 >
                  <NeoFromQuestAiEm2 >
                    {`Build new applications`}
                      </NeoFromQuestAiEm2>
                  <Frame1224 >
                    <Checkmark  src={`assets/food/images/checkmark_35.png`} alt={"checkmark"}/>
                    <Checkmark1  src={`assets/food/images/checkmark_34.png`} alt={"checkmark"}/>
                    <Checkmark2  src={`assets/food/images/checkmark_33.png`} alt={"checkmark"}/>
                  </Frame1224>
                </Frame1223>
              </Row1>
              <Row2 >
                <Divider5 >
                </Divider5>
                <Frame1225 >
                  <NeoFromQuestAiEm3 >
                    {`Generates react.js code`}
                      </NeoFromQuestAiEm3>
                  <Frame1226 >
                    <Checkmark3  src={`assets/food/images/checkmark_32.png`} alt={"checkmark"}/>
                    <Checkmark4  src={`assets/food/images/checkmark_31.png`} alt={"checkmark"}/>
                    <XMark  src={`assets/food/images/x_mark_35.png`} alt={"x mark"}/>
                  </Frame1226>
                </Frame1225>
              </Row2>
              <Row3 >
                <Divider6 >
                </Divider6>
                <Frame1227 >
                  <NeoFromQuestAiEm4 >
                    {`Integrates with the design and dev tools you love`}
                      </NeoFromQuestAiEm4>
                  <Frame1228 >
                    <Checkmark5  src={`assets/food/images/checkmark_30.png`} alt={"checkmark"}/>
                    <Checkmark6  src={`assets/food/images/checkmark_29.png`} alt={"checkmark"}/>
                    <XMark1  src={`assets/food/images/x_mark_34.png`} alt={"x mark"}/>
                  </Frame1228>
                </Frame1227>
              </Row3>
              <Row4 >
                <Divider7 >
                </Divider7>
                <Frame1229 >
                  <NeoFromQuestAiEm5 >
                    {`Add to existing applications easily`}
                      </NeoFromQuestAiEm5>
                  <Frame12210 >
                    <Checkmark7  src={`assets/food/images/checkmark_28.png`} alt={"checkmark"}/>
                    <XMark2  src={`assets/food/images/x_mark_33.png`} alt={"x mark"}/>
                    <XMark3  src={`assets/food/images/x_mark_32.png`} alt={"x mark"}/>
                  </Frame12210>
                </Frame1229>
              </Row4>
              <Row5 >
                <Divider8 >
                </Divider8>
                <Frame12211 >
                  <NeoFromQuestAiEm6 >
                    {`Design system support built-in`}
                      </NeoFromQuestAiEm6>
                  <Frame12212 >
                    <Checkmark8  src={`assets/food/images/checkmark_27.png`} alt={"checkmark"}/>
                    <XMark4  src={`assets/food/images/x_mark_31.png`} alt={"x mark"}/>
                    <XMark5  src={`assets/food/images/x_mark_30.png`} alt={"x mark"}/>
                  </Frame12212>
                </Frame12211>
              </Row5>
              <Row6 >
                <Divider9 >
                </Divider9>
                <Frame12213 >
                  <NeoFromQuestAiEm7 >
                    {`Component library support built-in (MUI)`}
                      </NeoFromQuestAiEm7>
                  <Frame12214 >
                    <Checkmark9  src={`assets/food/images/checkmark_26.png`} alt={"checkmark"}/>
                    <XMark6  src={`assets/food/images/x_mark_29.png`} alt={"x mark"}/>
                    <XMark7  src={`assets/food/images/x_mark_28.png`} alt={"x mark"}/>
                  </Frame12214>
                </Frame12213>
              </Row6>
              <Row7 >
                <Divider10 >
                </Divider10>
                <Frame12215 >
                  <NeoFromQuestAiEm8 >
                    {`Clean code with separation of concerns`}
                      </NeoFromQuestAiEm8>
                  <Frame12216 >
                    <Checkmark10  src={`assets/food/images/checkmark_25.png`} alt={"checkmark"}/>
                    <XMark8  src={`assets/food/images/x_mark_27.png`} alt={"x mark"}/>
                    <XMark9  src={`assets/food/images/x_mark_26.png`} alt={"x mark"}/>
                  </Frame12216>
                </Frame12215>
              </Row7>
              <Row8 >
                <Divider11 >
                </Divider11>
                <Frame12217 >
                  <NeoFromQuestAiEm9 >
                    {`Generates production-ready code`}
                      </NeoFromQuestAiEm9>
                  <Frame12218 >
                    <Checkmark11  src={`assets/food/images/checkmark_24.png`} alt={"checkmark"}/>
                    <XMark10  src={`assets/food/images/x_mark_25.png`} alt={"x mark"}/>
                    <XMark11  src={`assets/food/images/x_mark_24.png`} alt={"x mark"}/>
                  </Frame12218>
                </Frame12217>
              </Row8>
            </Frame122>
          </CompareChart>
        </Compare>
      </CompareSec>
      <CustomerQuote >
        <Box1 >
          <Text >
            <LeftSide1 >
              <Subtitle5 >
                <ActionsIcon6  src={`assets/food/images/Actions_Icon_16.png`} alt={"Actions Icon"}/>
                <CustomerLove >
                  {`CUSTOMER LOVE`}
                    </CustomerLove>
              </Subtitle5>
              <CustomerQuote1 >
                <Quote >
                  {`“Quest allows you to generate pixel perfect code from Figma designs in the fraction of the time that you would previously. Don’t even know why this wasn’t created before. “`}
                    </Quote>
                <Company >
                  <EnctrLogo  src={`assets/food/images/enctr_logo.png`} alt={"enctr logo"}/>
                  <Name >
                    <FullName >
                      {`Luka Antolic-Soban`}
                        </FullName>
                    <Title >
                      {`CEO of Entcr (a web3 company)`}
                        </Title>
                  </Name>
                </Company>
                <LearnMore2 >
                  <About2 >
                    {`Watch the`}
                      </About2>
                  <Link3 href="#" underline="hover"  >Success Story</Link3>
                </LearnMore2>
              </CustomerQuote1>
            </LeftSide1>
          </Text>
          <RightSide1 >
            <Luka1  src={`assets/food/images/Luka_1.png`} alt={"Luka 1"}/>
          </RightSide1>
        </Box1>
        <ProductHunt >
          <PhImage >
          </PhImage>
        </ProductHunt>
      </CustomerQuote>
      <DiscoverSec >
        <Frame127 >
          <Subtitle6 >
            <ActionsIcon7  src={`assets/food/images/Actions_Icon_15.png`} alt={"Actions Icon"}/>
            <NeoFromQuestAiEm10 >
              {`THE FUTURE of frontend`}
                </NeoFromQuestAiEm10>
          </Subtitle6>
          <DiscoverThe >
            <DiscoverTheSpan1  >{`Join the `}</DiscoverTheSpan1>
            <DiscoverTheSpan2  >{`future`}</DiscoverTheSpan2>
            <DiscoverTheSpan3  >{` & build products at rapid speed`}</DiscoverTheSpan3>
          </DiscoverThe>
          <ImportYourDifferen >
            {`The low-code movement is helping companies of all sizes remove redundant work. Quest enables you to build software products faster and go to market faster than ever.`}
              </ImportYourDifferen>
          <LearnMore3 >
            <About3 >
              {`Check out our`}
                </About3>
            <Link4 href="#" underline="hover"  >sample projects.</Link4>
          </LearnMore3>
          <ButtonOutlined2 variant="outlined" size="large" color="primary"    > Sign Up Now </ButtonOutlined2>
        </Frame127>
      </DiscoverSec>
      <BtmImage >
        <Sec4Image >
        </Sec4Image>
      </BtmImage>
    </Property1Desktop>
  );
}

export default Home;
