/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useCard18 = () => {
  let data = {};
  const handleButton = () => {};
  const Description = () => {};
  const text2 = () => {};
  const handleClose = () => {};

  let fns = {handleButton, Description, text2, handleClose};
  return {data, fns};
}

export default useCard18;