/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { Avatar } from '@mui/material';
import { styled } from '@mui/material/styles';

 
const Frame21 = styled("div")({  
  backgroundColor: `rgba(255, 255, 255, 1)`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: "100%",  
  height: "100%",  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
  overflow: `hidden`,  
});
  
const Avatar1 = styled(Avatar)({  
  position: `absolute`,  
  left: `109px`,  
  top: `70px`,  
  width: `24px`,  
  height: `24px`,  
});
  
const Avatar2 = styled(Avatar)({  
  width: `40px`,  
  height: `40px`,  
  position: `absolute`,  
  left: `156px`,  
  top: `62px`,  
});
  
const Avatar3 = styled(Avatar)({  
  position: `absolute`,  
  left: `8px`,  
  top: `50px`,  
  width: `40px`,  
  height: `40px`,  
});
  
const Avatar4 = styled(Avatar)({  
  position: `absolute`,  
  left: `72px`,  
  top: `114px`,  
  width: `40px`,  
  height: `40px`,  
});
  
const Avatar5 = styled(Avatar)({  
  position: `absolute`,  
  left: `256px`,  
  top: `106px`,  
  width: `32px`,  
  height: `32px`,  
});
  
const Avatar6 = styled(Avatar)({  
  position: `absolute`,  
  left: `136px`,  
  top: `114px`,  
  width: `40px`,  
  height: `40px`,  
});
  
const Frame3 = styled("img")({  
  height: `74px`,  
  width: `145px`,  
  objectFit: `cover`,  
  position: `absolute`,  
  left: `18px`,  
  top: `165px`,  
});
  
const Hello = styled("div")({  
  textAlign: `center`,  
  whiteSpace: `pre-wrap`,  
  color: `rgba(0, 0, 0, 1)`,  
  fontStyle: `normal`,  
  fontFamily: `Advent Pro`,  
  fontWeight: `400`,  
  fontSize: `20px`,  
  letterSpacing: `0.14000000059604645px`,  
  textDecoration: `none`,  
  lineHeight: `20px`,  
  textTransform: `none`,  
  position: `absolute`,  
  left: `169px`,  
  top: `187px`,  
});
 
function Frame2(props) {
  return (
    <Frame21 className={props.className} >
      <Avatar1 variant="square" src={`hello/world/Frame2_Avatar_2.png`} alt={"Avatar"}   />
      <Avatar2 variant="rounded" src={`hello/world/Frame2_Avatar_1.png`} alt={"Avatar"}   />
      <Avatar3 variant="circular" src={`hello/world/Frame2_Avatar.png`} alt={"Avatar"}   />
      <Avatar4 variant="square"  >OP</Avatar4>
      <Avatar5 variant="square"  >OP</Avatar5>
      <Avatar6 variant="rounded"  >OP</Avatar6>
      <Frame3  src={`hello/world/Frame2_Frame_3.jpg`} alt={"Frame 3"}/>
      <Hello >
        {`hello`}
          </Hello>
    </Frame21>
  );
}

export default Frame2;
