/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';
import Frame61Image from 'src/assets/food/images/Frame6_Frame_6.png';

 
const Frame61 = styled("div")({  
  backgroundImage: `url(${Frame61Image})`,  
  backgroundPosition: `center`,  
  backgroundSize: `cover`,  
  backgroundRepeat: `no-repeat`,  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `row`,  
  width: `119px`,  
  height: `101px`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  overflow: `hidden`,  
});
 
function Frame6(props) {
  return (
    <Frame61 className={props.className} >
    </Frame61>
  );
}

export default Frame6;
